var:
  nacos:
    addr: test.nacos-in.hifor.net:8848
    username: nacos-sample
    password: "Ry*UuP6#k$VE^BLr"
    namespace: de16af61-c5b9-41ec-b594-6c7e88bb57ca
    group: sample-group

server:
  #default port 8080
  port: 8989

spring:
  cloud:
# 配置无效
#    config:
#      # 是否不覆盖其他属性源，默认为false，即覆盖其他源
#      override-none: false
#      # 允许nacos被本地文件覆盖，默认为true
#      allow-override: true
#      # 是否覆盖系统属性源，默认为true
#      override-system-properties: true
    nacos:
      config:
        server-addr: ${var.nacos.addr}
        username: ${var.nacos.username}
        password: ${var.nacos.password}
        namespace: ${var.nacos.namespace}
        group: ${var.nacos.group}
  config:
    import:
      - optional:nacos:config-common.yml
      - optional:nacos:test.yml
#      - optional:nacos:test01.yml?group=group_01 # 覆盖默认 group，监听 group_01:test01.yml
#      - optional:nacos:test02.yml?group=group_02&refreshEnabled=false # 不开启动态刷新
#      - nacos:test03.yml # 在拉取nacos配置异常时会快速失败，会导致 spring 容器启动失败